# Generated by Django 2.1.7 on 2019-04-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentName', models.CharField(max_length=100)),
                ('agentId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentId', models.IntegerField(null=True)),
                ('answerType', models.CharField(max_length=20)),
                ('answer', models.TextField()),
                ('intentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentApi.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='IntentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentCategoryName', models.CharField(max_length=100)),
                ('accountId', models.IntegerField()),
                ('campaignId', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('parentIntentCategoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('splitSentence', models.TextField()),
                ('intentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentApi.Intent')),
            ],
        ),
        migrations.AddField(
            model_name='intent',
            name='intentCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentApi.IntentCategory'),
        ),
    ]
